name: Auto Tag on Push

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Mod Version from gradle.properties
        id: get_version
        run: |
          VERSION=$(grep '^mod_version' gradle.properties | cut -d'=' -f2 | xargs)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "$VERSION"

      - name: Create and Push Tag
        run: |
          TAG_NAME="v${{ env.VERSION }}"
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "$TAG_NAME"
          else
            git tag $TAG_NAME
            git push origin $TAG_NAME
          fi